/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.2/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    alias(libs.plugins.interop.docker.integration) apply false
    alias(libs.plugins.interop.junit) apply false
    alias(libs.plugins.interop.spring.boot) apply false
    alias(libs.plugins.interop.server.publish) apply false
    alias(libs.plugins.interop.server.version)
    alias(libs.plugins.interop.version.catalog)

    // We need to force IntelliJ to do some actions they expose through this plugin.
    alias(libs.plugins.idea.ext)
}
