/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.2/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    alias(libs.plugins.interop.docker.integration) apply false
    alias(libs.plugins.interop.junit) apply false
    alias(libs.plugins.interop.spring.boot) apply false
    alias(libs.plugins.interop.spring.framework) apply false
    alias(libs.plugins.interop.server.publish) apply false
    alias(libs.plugins.interop.server.version)
    alias(libs.plugins.interop.version.catalog)
//    alias(libs.plugins.interop.sonarqube)
    id("org.sonarqube") version "4.4.1.3373"

    // We need to force IntelliJ to do some actions they expose through this plugin.
    alias(libs.plugins.idea.ext)
}

sonar {
    properties {
        property("sonar.projectKey", project.rootProject.name)
    }
}

subprojects {
    apply(plugin = "com.projectronin.interop.gradle.base")

    if (project.name != "clinical-trial-server") {
        apply(plugin = "com.projectronin.interop.gradle.server-publish")
    }

    sonar {
        properties {
            property("sonar.sources", "src/main")
            property("sonar.tests", "src/test")
        }
    }
}
