services:
  clinical-one-server:
    restart: on-failure
    build:
      context: ./clinical-trial-server
      dockerfile: Dockerfile
    image: clinical-trial-server:local
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://springuser:ThePassword@clinical-trial-db:3306/clinical-trial-db
    ports:
      - "8080:8080"
    depends_on:
      clinical-trial-db:
        condition: service_healthy

  clinical-trial-db:
    restart: always
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_DATABASE=clinical-trial-db
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "springuser", "-pThePassword" ]
      timeout: 5s
      retries: 3
