package com.projectronin.clinical.trial.server.clinicalone.model

data class ClinicalOneGetStudyNameResponse(
    val status: String? = null,
    val result: List<ClinicalOneGetStudyNameResponseResult>? = listOf(),
    val errorData: String? = null,
    val version: Int? = null,
) {
    data class ClinicalOneGetStudyNameResponseResult(
        val identity: String? = null,
        val id: String? = null,
        val version: String? = null,
        val versionStart: String? = null,
        val versionEnd: String? = null,
        val studyTitle: String? = null,
        val studyDescription: String? = null,
        val contractCode: String? = null,
        val versionTitle: String? = null,
        val studyPhase: String? = null,
        val therapeuticArea: String? = null,
        val openLabelBlinded: String? = null,
        val studyStatus: String? = null,
        val versionPreviousStatus: String? = null,
        val versionStatus: String? = null,
        val versionType: String? = null,
        val hasObjects: Int? = null,
        val draftVersionsCount: Int? = null,
        val testingVersionsCount: Int? = null,
        val approvedVersionsCount: Int? = null,
        val archivedVersionsCount: Int? = null,
        val everApprovedCount: Int? = null,
        val modes: List<String>? = listOf(),
        val customerRefNo: String? = null,
        val description: String? = null,
        val singleKitSettingId: String? = null,
        val sowNo: String? = null,
        val sponsorId: String? = null,
        val studyStatusId: Int? = null,
        val useBlindingGroups: Boolean? = null,
        val useLabelGroups: Boolean? = null,
        val useShippinggroups: Boolean? = null,
        val previousState: String? = null,
        val studyState: String? = null,
        val lastModified: String? = null,
        val systemCodeListId: String? = null,
        val companies: String? = null,
        val companyLabels: String? = null,
    )
}
