name: Lint
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: oci-shared
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: projectronin/github/.github/actions/setup-jdk-build@setup-jdk-build/v1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradlew Ktlint
        run: ./gradlew ktlintCheck
