name: Clinical Trial Server Tests
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: projectronin/github/.github/actions/setup-jdk-build@setup-jdk-build/v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradlew Test
        run: ./gradlew :clinical-trial-server:test
